# Form implementation generated from reading ui file '/home/manu/Proyecto_interfaces/templates/dlg_filtrar_propiedades.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DlgFiltrarPropiedades(object):
    def setupUi(self, DlgFiltrarPropiedades):
        DlgFiltrarPropiedades.setObjectName("DlgFiltrarPropiedades")
        DlgFiltrarPropiedades.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        DlgFiltrarPropiedades.resize(400, 300)
        DlgFiltrarPropiedades.setModal(True)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=DlgFiltrarPropiedades)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 381, 233))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        self.cmb_pro_tipo_filtrar = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.cmb_pro_tipo_filtrar.setObjectName("cmb_pro_tipo_filtrar")
        self.gridLayout.addWidget(self.cmb_pro_tipo_filtrar, 2, 1, 1, 1)
        self.cmb_pro_municipio_filtrar = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.cmb_pro_municipio_filtrar.setObjectName("cmb_pro_municipio_filtrar")
        self.gridLayout.addWidget(self.cmb_pro_municipio_filtrar, 4, 2, 1, 1)
        self.cmb_pro_provincia_filtrar = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.cmb_pro_provincia_filtrar.setObjectName("cmb_pro_provincia_filtrar")
        self.gridLayout.addWidget(self.cmb_pro_provincia_filtrar, 4, 0, 1, 1)
        self.btn_pro_filtrar = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.btn_pro_filtrar.setObjectName("btn_pro_filtrar")
        self.gridLayout.addWidget(self.btn_pro_filtrar, 6, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem1, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem2, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(70, 70))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/home/manu/Proyecto_interfaces/templates/../img/house.ico"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem3, 1, 1, 1, 1)

        self.retranslateUi(DlgFiltrarPropiedades)
        QtCore.QMetaObject.connectSlotsByName(DlgFiltrarPropiedades)

    def retranslateUi(self, DlgFiltrarPropiedades):
        _translate = QtCore.QCoreApplication.translate
        DlgFiltrarPropiedades.setWindowTitle(_translate("DlgFiltrarPropiedades", "Filtrar Propiedades"))
        self.btn_pro_filtrar.setText(_translate("DlgFiltrarPropiedades", "Buscar"))
