# Form implementation generated from reading ui file '/home/manu/Proyecto_interfaces/templates/DlgCalendar.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DlgCalendar(object):
    def setupUi(self, DlgCalendar):
        DlgCalendar.setObjectName("DlgCalendar")
        DlgCalendar.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        DlgCalendar.resize(500, 185)
        DlgCalendar.setMinimumSize(QtCore.QSize(500, 185))
        DlgCalendar.setMaximumSize(QtCore.QSize(500, 185))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/manu/Proyecto_interfaces/templates/../img/house.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        DlgCalendar.setWindowIcon(icon)
        DlgCalendar.setModal(True)
        self.Calendar = QtWidgets.QCalendarWidget(parent=DlgCalendar)
        self.Calendar.setGeometry(QtCore.QRect(0, 0, 500, 183))
        self.Calendar.setMinimumSize(QtCore.QSize(500, 183))
        self.Calendar.setMaximumSize(QtCore.QSize(500, 183))
        self.Calendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.VerticalHeaderFormat.NoVerticalHeader)
        self.Calendar.setObjectName("Calendar")

        self.retranslateUi(DlgCalendar)
        QtCore.QMetaObject.connectSlotsByName(DlgCalendar)

    def retranslateUi(self, DlgCalendar):
        _translate = QtCore.QCoreApplication.translate
        DlgCalendar.setWindowTitle(_translate("DlgCalendar", "Selecciona fecha"))
