# Form implementation generated from reading ui file '.\\templates\\dlg_buscar_propiedad.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DlgBuscarPropiedad(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(273, 222)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.cmb_buscar_pro_municipio = QtWidgets.QComboBox(parent=Dialog)
        self.cmb_buscar_pro_municipio.setMinimumSize(QtCore.QSize(200, 0))
        self.cmb_buscar_pro_municipio.setMaximumSize(QtCore.QSize(200, 16777215))
        self.cmb_buscar_pro_municipio.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.cmb_buscar_pro_municipio.setEditable(True)
        self.cmb_buscar_pro_municipio.setObjectName("cmb_buscar_pro_municipio")
        self.verticalLayout.addWidget(self.cmb_buscar_pro_municipio, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.btn_buscar_pro = QtWidgets.QPushButton(parent=Dialog)
        self.btn_buscar_pro.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_buscar_pro.setObjectName("btn_buscar_pro")
        self.verticalLayout.addWidget(self.btn_buscar_pro, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Elige el Municipio"))
        self.btn_buscar_pro.setText(_translate("Dialog", "Importar"))
