# Form implementation generated from reading ui file '.\\templates\\dlgGestipoprop.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgGestion(object):
    def setupUi(self, dlgGestion):
        dlgGestion.setObjectName("dlgGestion")
        dlgGestion.resize(400, 300)
        dlgGestion.setMinimumSize(QtCore.QSize(400, 300))
        dlgGestion.setMaximumSize(QtCore.QSize(400, 300))
        self.widget = QtWidgets.QWidget(parent=dlgGestion)
        self.widget.setGeometry(QtCore.QRect(30, 20, 331, 251))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame.setObjectName("frame")
        self.lblGestipoprop = QtWidgets.QLabel(parent=self.frame)
        self.lblGestipoprop.setGeometry(QtCore.QRect(30, 20, 280, 30))
        self.lblGestipoprop.setMinimumSize(QtCore.QSize(280, 30))
        self.lblGestipoprop.setMaximumSize(QtCore.QSize(280, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblGestipoprop.setFont(font)
        self.lblGestipoprop.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblGestipoprop.setObjectName("lblGestipoprop")
        self.txtGestipoprop = QtWidgets.QLineEdit(parent=self.frame)
        self.txtGestipoprop.setGeometry(QtCore.QRect(80, 60, 150, 20))
        self.txtGestipoprop.setMinimumSize(QtCore.QSize(150, 20))
        self.txtGestipoprop.setMaximumSize(QtCore.QSize(150, 20))
        self.txtGestipoprop.setObjectName("txtGestipoprop")
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAltatipoprop = QtWidgets.QPushButton(parent=self.widget)
        self.btnAltatipoprop.setMinimumSize(QtCore.QSize(80, 25))
        self.btnAltatipoprop.setMaximumSize(QtCore.QSize(80, 25))
        self.btnAltatipoprop.setObjectName("btnAltatipoprop")
        self.horizontalLayout.addWidget(self.btnAltatipoprop)
        self.btnDeltipoprop = QtWidgets.QPushButton(parent=self.widget)
        self.btnDeltipoprop.setMinimumSize(QtCore.QSize(80, 25))
        self.btnDeltipoprop.setMaximumSize(QtCore.QSize(80, 25))
        self.btnDeltipoprop.setObjectName("btnDeltipoprop")
        self.horizontalLayout.addWidget(self.btnDeltipoprop)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(dlgGestion)
        QtCore.QMetaObject.connectSlotsByName(dlgGestion)

    def retranslateUi(self, dlgGestion):
        _translate = QtCore.QCoreApplication.translate
        dlgGestion.setWindowTitle(_translate("dlgGestion", "Gestión Tipo Propiedades"))
        self.lblGestipoprop.setText(_translate("dlgGestion", "Introduzca tipo de propiedad a crear o eliminar"))
        self.btnAltatipoprop.setText(_translate("dlgGestion", "Alta"))
        self.btnDeltipoprop.setText(_translate("dlgGestion", "Eliminar"))
