# Form implementation generated from reading ui file '/home/manu/Proyecto_interfaces/templates/dlgGestipoprop.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgGestion(object):
    def setupUi(self, dlgGestion):
        dlgGestion.setObjectName("dlgGestion")
        dlgGestion.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        dlgGestion.resize(400, 300)
        dlgGestion.setMinimumSize(QtCore.QSize(400, 300))
        dlgGestion.setMaximumSize(QtCore.QSize(400, 300))
        dlgGestion.setModal(True)
        self.frame = QtWidgets.QFrame(parent=dlgGestion)
        self.frame.setGeometry(QtCore.QRect(10, 20, 371, 261))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 342, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(50, 50))
        self.label.setMaximumSize(QtCore.QSize(50, 50))
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/home/manu/Proyecto_interfaces/templates/../img/house.ico"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblGestipoprop = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.lblGestipoprop.setMinimumSize(QtCore.QSize(280, 30))
        self.lblGestipoprop.setMaximumSize(QtCore.QSize(280, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblGestipoprop.setFont(font)
        self.lblGestipoprop.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblGestipoprop.setObjectName("lblGestipoprop")
        self.horizontalLayout_3.addWidget(self.lblGestipoprop)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.txtGestipoprop = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.txtGestipoprop.setMinimumSize(QtCore.QSize(150, 20))
        self.txtGestipoprop.setMaximumSize(QtCore.QSize(150, 20))
        self.txtGestipoprop.setObjectName("txtGestipoprop")
        self.horizontalLayout_4.addWidget(self.txtGestipoprop)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAltatipoprop = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btnAltatipoprop.setMinimumSize(QtCore.QSize(80, 25))
        self.btnAltatipoprop.setMaximumSize(QtCore.QSize(80, 25))
        self.btnAltatipoprop.setObjectName("btnAltatipoprop")
        self.horizontalLayout.addWidget(self.btnAltatipoprop)
        self.btnDeltipoprop = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btnDeltipoprop.setMinimumSize(QtCore.QSize(80, 25))
        self.btnDeltipoprop.setMaximumSize(QtCore.QSize(80, 25))
        self.btnDeltipoprop.setObjectName("btnDeltipoprop")
        self.horizontalLayout.addWidget(self.btnDeltipoprop)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(dlgGestion)
        QtCore.QMetaObject.connectSlotsByName(dlgGestion)

    def retranslateUi(self, dlgGestion):
        _translate = QtCore.QCoreApplication.translate
        dlgGestion.setWindowTitle(_translate("dlgGestion", "Gestión Tipo Propiedades"))
        self.lblGestipoprop.setText(_translate("dlgGestion", "Introduzca tipo de propiedad a crear o eliminar"))
        self.btnAltatipoprop.setText(_translate("dlgGestion", "Alta"))
        self.btnDeltipoprop.setText(_translate("dlgGestion", "Eliminar"))
